services:
    infra.serializer.service:
        class: Infrastructure\Service\SerializerService
        arguments: ['@jms_serializer']

    infra.json_response.service:
        class: Infrastructure\Service\JsonResponseService
        arguments: ['@infra.serializer.service']