services:
    app.oportunidade.service:
        class: AppBundle\Service\OportunidadeService
        arguments: ['@oportunidade.repository']

    app.inscricao.service:
        class: AppBundle\Service\InscricaoService
        arguments: ['@inscricao.repository', '@infra.storage.service', '@onesignal.api']

    app.cargo.service:
        class: AppBundle\Service\CargoService
        arguments: ['@cargo.repository', '@infra.storage.service']
